### PR TITLE
[LIEF-13331] Support Sidekiq 6

### LINKED ISSUE #13: Fix for Sidekiq 6
It looks like the gem currently doesn't work with Sidekiq 6:

```
NameError: uninitialized constant Sidekiq::Logging
/var/lib/jenkins/workspace/executor-4/job-backend-pr/.gems/gems/loggery-0.2.1/lib/loggery/sidekiq/setup.rb:7:in `setup'
/var/lib/jenkins/workspace/executor-4/job-backend-pr/.gems/gems/loggery-0.2.1/lib/loggery.rb:21:in `setup_sidekiq'
```

That's because of the breaking changes related to logging - https://github.com/mperham/sidekiq/blob/master/6.0-Upgrade.md.

Ideally we should support both Sidekiq 5 and 6, but that depends on how difficult that is.

### PR DESCRIPTION
**Pull request by tiagotex**
Fixes #13

### CODE REVIEW

File: Appraisals [hunk 1]
```diff
@@ -13,5 +13,9 @@ appraise "rails5.1" do
 end
 
 appraise "rails5.2" do
-  gem "rails", "5.2.0.beta2"
+  gem "rails", "5.2.0"
+end
+
+appraise "rails6.0" do
+  gem "rails", "6.0.0"
```
Comment (adamniedzielski) [inline Appraisals]: And same here

File: lib/loggery/gem/version.rb [hunk 2]
```diff
@@ -2,6 +2,6 @@
 
 module Loggery
   module Gem
-    VERSION = "0.2.1"
+    VERSION = "0.3.0"
```
Comment (adamniedzielski) [inline lib/loggery/gem/version.rb]: Great, we will be able to release as soon as we merge.

File: lib/loggery/sidekiq/setup.rb [hunk 3]
```diff
@@ -4,9 +4,9 @@ module Loggery
   module Sidekiq
     module Setup
       def self.setup
-        ::Sidekiq::Logging.logger = Rails.logger
-
         ::Sidekiq.configure_server do |config|
+          config.logger = Rails.logger
```
Comment (adamniedzielski) [inline lib/loggery/sidekiq/setup.rb]: Just out of curiosity: will this work with Sidekiq < 6 as well?

File: .travis.yml [hunk 4]
```diff
@@ -1,16 +1,15 @@
 sudo: false
 language: ruby
 rvm:
-  - 2.4.2
+  - 2.6.4
```
Comment (adamniedzielski) [inline .travis.yml]: Can we test it on Ruby 2.5 as well? I think that it makes sense at least until we upgrade all our apps to Ruby 2.6

File: .travis.yml [hunk 5]
```diff
@@ -1,16 +1,15 @@
...
 gemfile:
   - gemfiles/rails4.2.gemfile
   - gemfiles/rails5.0.gemfile
   - gemfiles/rails5.1.gemfile
```
Comment (adamniedzielski) [inline .travis.yml]: I think that we can remove `4.2`, `5.0`, and `5.1` to cut the test running time and because they're no longer supported.

File: .rubocop.yml [hunk 6]
```diff
@@ -1,5 +1,5 @@
 AllCops:
-  TargetRubyVersion: 2.3
+  TargetRubyVersion: 2.6
```
Comment (adamniedzielski) [inline .rubocop.yml]: Could we target Ruby 2.5, assuming that we want to test it on Travis? (see my other comment)

File: lib/loggery/metadata/middleware/sidekiq.rb [hunk 7]
```diff
@@ -19,14 +19,12 @@ def call(_worker, message, queue)
...
-                # the time they reach the Sidekiq default error handler.
-                self.class.error_handler&.call(e)
-                raise e
-              end
+              yield
+            rescue StandardError => e
+              # Log exceptions here, otherwise they won't have the metadata available anymore by
+              # the time they reach the Sidekiq default error handler.
+              self.class.error_handler&.call(e)
+              raise e
```
Comment (adamniedzielski) [inline lib/loggery/metadata/middleware/sidekiq.rb]: What's the minimal version of Ruby that supports `rescue` outside `begin` / `end`?

File: lib/loggery/sidekiq/setup.rb (hunk 3 above)
Comment (tiagotex) [reply lib/loggery/sidekiq/setup.rb]: it does

File: lib/loggery/metadata/middleware/sidekiq.rb (hunk 7 above)
Comment (tiagotex) [reply lib/loggery/metadata/middleware/sidekiq.rb]: As far as I'm aware it's 2.5

**Comment by adamniedzielski** [comment]
Awesome 🎉
